[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'


#
#  APPEARANCE
#

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#tabline#enabled = 1
    " let g:airline#extensions#tabline#buffer_idx_mode = 1
    let g:airline#extensions#tabline#buffer_nr_show = 1
    let g:airline#extensions#whitespace#mixed_indent_algo = 1
    let g:airline#extensions#ale#enabled = 1
    nmap <C-j> <Plug>AirlineSelectPrevTab
    nmap <C-k> <Plug>AirlineSelectNextTab
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
    " let g:airline_theme='powerlineish'
'''

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
    " If you have vim >=8.0 or Neovim >= 0.1.5
    if (has("termguicolors"))
      set termguicolors
    endif

    " For Neovim 0.1.3 and 0.1.4
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1

    " Theme
    " syntax enable
    " colorscheme tender
    " let g:airline_theme = 'tender'
'''

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
    syntax enable
    colorscheme molokai
    let g:airline_theme = 'molokai'
'''

[[plugins]]
repo = 'srcery-colors/srcery-vim'
hook_add = '''
    " colorscheme srcery
'''

[[plugins]]
repo = 'sickill/vim-monokai'
hook_add = '''
    " syntax enable
    " colorscheme monokai
'''

#
#  UTILITIES
#

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
    let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'map <C-n> :NERDTreeToggle<CR>'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    let g:ale_linters = {
    \   'python': ['pylint'],
    \}
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_update = '''
  let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = "let g:previm_open_cmd = 'google-chrome-stable'"

[[plugins]]
repo = 'Townk/vim-autoclose'


#
#  LANGUAGE SUPPORT
#

[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = 'au BufRead,BufNewFile *.md set filetype=markdown'

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
    let g:rustfmt_autosave = 1
    let g:rustfmt_command = "$HOME/.cargo/bin/rustfmt"
'''

[[plugins]]
repo = 'racer-rust/vim-racer'
hook_add = '''
    set hidden
    let g:racer_insert_paren = 1
    let g:racer_cmd = "$HOME/.cargo/bin/racer"
'''

[[plugins]]
repo = 'derekwyatt/vim-scala'

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
    let g:go_highlight_functions = 1
    let g:go_highlight_methods = 1
    let g:go_highlight_structs = 1
    let g:go_highlight_methods = 1
    let g:go_highlight_operators = 1
    let g:go_highlight_extra_types = 1
'''

[[plugins]]
repo = 'rhysd/vim-crystal'

[[plugins]]
repo = 'kana/vim-filetype-haskell'

[[plugins]]
repo = 'nbouscal/vim-stylish-haskell'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'

[[plugins]]
repo = 'cespare/vim-toml'
