[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'


#
#  APPEARANCE
#

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#tabline#enabled = 1
    " let g:airline#extensions#tabline#buffer_idx_mode = 1
    let g:airline#extensions#tabline#buffer_nr_show = 1
    let g:airline#extensions#whitespace#mixed_indent_algo = 1
    let g:airline#extensions#ale#enabled = 1
    nmap <C-j> <Plug>AirlineSelectPrevTab
    nmap <C-k> <Plug>AirlineSelectNextTab
'''

[[plugins]]
repo = 'tomasiser/vim-code-dark'
hook_add = '''
colorscheme codedark
let g:airline_theme = 'codedark'
'''


#
#  UTILITIES
#

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
    let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'map <C-n> :NERDTreeToggle<CR>'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    let g:ale_sign_column_always = 1
    let g:ale_fix_on_save = 1
    let g:ale_completion_enabled = 1
    let g:ale_sign_error = '⨉'
    let g:ale_sign_warning = '⚠'
    let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
    let g:ale_linters = {
    \   'python': ['pylint', 'mypy'],
    \}
    let g:ale_fixers = {
    \   '*': ['remove_trailing_lines', 'trim_whitespace'],
    \}
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_update = '''
  let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = "let g:previm_open_cmd = 'google-chrome-stable'"

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'


#
#  LANGUAGE SUPPORT
#

[[plugins]]
repo = 'numirias/semshi'

[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = '''
    au BufRead,BufNewFile *.md set filetype=markdown
    let g:tex_conceal = ""
    let g:vim_markdown_math = 1
    let g:vim_markdown_conceal = 0
    let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
    let g:rustfmt_autosave = 1
    let g:rustfmt_command = "$HOME/.cargo/bin/rustfmt"
'''

[[plugins]]
repo = 'racer-rust/vim-racer'
hook_add = '''
    set hidden
    let g:racer_insert_paren = 1
    let g:racer_cmd = "$HOME/.cargo/bin/racer"
'''

[[plugins]]
repo = 'derekwyatt/vim-scala'

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
    let g:go_highlight_functions = 1
    let g:go_highlight_methods = 1
    let g:go_highlight_structs = 1
    let g:go_highlight_methods = 1
    let g:go_highlight_operators = 1
    let g:go_highlight_extra_types = 1
'''

[[plugins]]
repo = 'rhysd/vim-crystal'

[[plugins]]
repo = 'kana/vim-filetype-haskell'

[[plugins]]
repo = 'nbouscal/vim-stylish-haskell'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'lervag/vimtex'
hook_add = '''
    let g:vimtex_compiler_progname = 'nvr'
    let g:vimtex_compiler_latexmk_engines = { '_' : '-pdfdvi' }
    let g:vimtex_compiler_latexmk = { 'continuous' : 0 }
    let g:vimtex_quickfix_open_on_warning = 0
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
set hidden

let g:LanguageClient_serverCommands = {
    \ 'ruby': ['~/.rbenv/shims/solargraph', 'stdio'],
    \ }

nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
'''
